### ISSUE TITLE
How is this related to Twelve-Factor?

### ISSUE THREAD

**Issue by z0u** [luggit/react-native-config#181]
Honest question from someone learning about 12 factor: the README says:

> Bring some [12 factor][1] love to your mobile apps!

But the linked 12 factor page explicitly says to use environment variables instead of config files.

[1]: https://12factor.net/config

**Comment by pedro** [comment]
Amazing question!

At first `.env` may not seem very different than something like `config.js`. I've seen a lot of RN apps specifying their configs in a js file; that's already pretty good if these files are not checked into version control – although still not perfect since they're language-specific (very relevant for us here considering we want to use the same file to work with Android, iOS and JS).

The other problem with these files is that they they tend to grow ugly as you add more environments.

But I digress – you're right, 12 Factor encourages using the env instead of a config file. It's just that `.env` is pretty close to the former: it's really just an snapshot of the environment, without it you'd potentially have to type `export API_URL=...` whenever running your program/script locally.

And what most of the libraries supporting `.env` do is to really just load that environment into your process. The app then just uses the standard lib to read values from the env, which means they don't depend on the actual `.env` file, a nice benefit for service-side apps as different platforms have different ways to specify the env.

This is where we depart from other libraries, and from 12 factor itself. We actually don't expose variables in the environment, if anything because with mobiles apps we have the build and the runtime environment, it would be a bit weird to conflate these. And that's fine, the 12 Factor is a set of standard for "applications which run as a service". They're not intended for UI apps, although many concepts are still useful on this level.

Hope this helps! I'll close the issue but happy to clarify anything else/etc.

**Comment by z0u** [comment]
Ah, thanks for that explanation - now I see where the desire comes from, since in the case of React Native you want to set the variables at build time. I see there's also [a way to do this][1] with Babel - something for me to ponder. Cheers!

[1]: https://github.com/babel/minify/blob/master/packages/babel-plugin-transform-inline-environment-variables/README.md
