### ISSUE TITLE
Does this package actually use system environment files?

### ISSUE THREAD

**Issue by mrozbarry** [luggit/react-native-config#271]
I was looking through the native code (but I'm not overly strong in Java or Objective-C in comparison to Javascript), and it looks like this is purely loading data from the chosen .env* file. Why is that?

My use case is my team wants to use visual studio app center, and we don't want to commit private keys to our code repo, thus we don't want to commit our .env file (specifically, our production version). What I want is to be able to read from the system environment if a value (or whole file) isn't accessible. This would let me set up proper environment variables in my build process without having to expose my variables/data to the public.

What would be nice is if I could white-list a set of system variables that would get automatically picked up on the building system and injected into my build without exposing anything else.

Is that something this package could/should cover, or is there a different package I should be checking out?

**Comment by erickreutz** [comment]
The general workflow is to add a .env file and then add the file to your .gitignore or similar vcs file so it is never committed. Will this not work for you?

**Comment by timLoewel** [comment]
But how should the .env variables come to the ci-build system?
If I want the ci-server to build a production release, it has to have access to the secret variables.
But those variables are not supposed to be in the repository.

Most ci-systems have a mechanism, that one can specify secret variables, that are then used in the build (e.g. https://docs.gitlab.com/ee/ci/variables/#variables).

@mrozbarry 's idea would combine the two ways of defining environment variables.

So what is the currently recommended way of getting secrets to the ci server?

**Comment by mrozbarry** [comment]
From _The Twelve-Factor App_, linked from README.md (with my own added emphasis):

> The twelve-factor app stores config in environment variables (often shortened to env vars or env). **Env vars are easy to change between deploys without changing any code; unlike config files, there is little chance of them being checked into the code repo accidentally**; and unlike custom config files, or other config mechanisms such as Java System Properties, they are a language- and OS-agnostic standard.

I think either this library needs to not say it follows 12-factor or it needs to accept environment variables properly. I originally wanted to use this library because it initially appeared to follow 12-factor, but it clearly does not completely, and particularly in the way that makes app config/secrets secure.

**Comment by mrozbarry** [comment]
Opened a PR that _might_ work, but I need some people who do real java/objective-c to review/make some suggestions.

**Comment by pedro** [comment]
Hey folks! Sorry I dropped the ball here.

You're right this package doesn't quite implement 12-factor. I just mentioned it briefly in the readme because of that, will think of a better way to frame it.

In practice we're observing a subset of that "factor" here: the idea that app configuration should leave outside the code, and be language and OS agnostic.

Your pull making the configuration actually live in the system environment is very interesting, but I'd avoid that direction for UI/mobile applications. 12 Factor applies mostly to server-side applications, a lot of the patterns there don't quite apply here.

For configuration in particular the challenge with the system environment is that there are several of them: gradle, xcode, fastlane, etc. Just seems like it will be extremely hard to get all of those to play well with the system env. And even if we do, we'll have to handle collisions or unwanted variables exposed with the app (for instance, if you have AWS keys in your env then we'll need to make sure it's not bundled with the app).

I think that's why even more traditional server-side applications do rely on `.env` files and something like [foreman](https://github.com/ddollar/foreman).

Anyways – thanks for starting the discussion and the awesome pull, it does seem like some people are using it regardless 👌

**Comment by ankitsehgal94** [comment]
Hey @mrozbarry.
I am using this package but gitlab ci looks for .env during deployment stage and my .env is in .gitignore. so it shows "missing .env file"
Is there any way I can solve this issue?

**Comment by mrozbarry** [comment]
This issue and related PR were abandoned two years ago, and I'm not a contributor to this repo. @pedro sounds like he's the person to ask, not me.

**Comment by akmalahmed525** [comment]
> Hey @mrozbarry.
> I am using this package but gitlab ci looks for .env during deployment stage and my .env is in .gitignore. so it shows "missing .env file"
> Is there any way I can solve this issue?

Yes, I'm also facing this issue. 
How can we access the missing .env file in CI/CD systems.

**Comment by arnoldc** [comment]
a traditional CI can create .env  this can be done via a command 
and the following values can be created in your CI Secret variables
