### ISSUE TITLE
Not working with RN 0.60.4

### ISSUE THREAD

**Issue by ravimaurya-nickelfox** [luggit/react-native-config#365]
The library is not working with `RN 0.60.4`, automatic linking is not working. If I try to link manually, it throws errors. On `pod install` it produces error `'GeneratedDotEnv.m' file not found`. 

Any help? 🆘

**Comment by Elvinra** [comment]
You are using react-native-config from npmjs, try to use this librairy directly from github
yarn add https://github.com/luggit/react-native-config

**Comment by gwmccull** [comment]
I ended up using this specific commit and then I didn't need the post-install scripts mentioned in other issues
github.com/luggit/react-native-config.git#89a602b

**Comment by ravimaurya-nickelfox** [comment]
@Elvinra that worked for me!!

Another fix, if you install with npmjs, then
``` yarn add react-native-config```
Open podfile and add
```ruby
post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'react-native-config'
     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
     phase.shell_script = "cd ../../"\
     " && RNC_ROOT=./node_modules/react-native-config/"\
     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
     
     target.build_phases << phase
     target.build_phases.move(phase,0)
   end
 end
end
```

`cd iOS && pod install`

**Comment by dineshmm23** [comment]
Please check that node_modules/react-native-config/ios/ReactNativeConfig contains same up to date files from repo.

Nevermind, just found out that this repo is updated but not published to npm.
Replace "react-native-toasty": "0.0.4" with "react-native-config": "git+https://github.com/luggit/react-native-config.git"

Then you can run pod install without issue.

Still I don't understand why the npm version is not updated anymore.

**Comment by GuillaumeMunsch** [comment]
Credit goes to @bockc here https://github.com/prscX/react-native-toasty/issues/12#issuecomment-514209713

**Comment by fariasmark** [comment]
I need help! I've try @dineshmm23's solution but I'm still getting this error:

ruby: No such file or directory -- ./node_modules/react-native-config//ios/ReactNativeConfig/BuildDotenvConfig.ruby (LoadError)

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by gwmccull** [comment]
@fariasmark Are you missing the script? What version of `react-native-config` and `react-native` are you using? 

The error that you reported is not the same as the original issue so you may want to open your own issue

**Comment by ravimaurya-nickelfox** [comment]
@fariasmark just follow these steps:

`yarn add react-native-config`

then go to `ios>Podfile` and add below code at the bottom of file.

```ruby
post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'react-native-config'
     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
     phase.shell_script = "cd ../../"\
     " && RNC_ROOT=./node_modules/react-native-config/"\
     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
     
     target.build_phases << phase
     target.build_phases.move(phase,0)
   end
 end
end
```

then run `pod install`

now run `react-native run-ios`

**Comment by mchudy** [comment]
@fariasmark Try replacing `BuildDotenvConfig.ruby` with `BuildDotenvConfig.rb`. It helped in my case.

**Comment by s123121** [comment]
Here is the guide for some poor soul javascript dev like me out there: 
1. `yarn add luggit/react-native-config#master` (don't use the version on npm or you will spend way too much time to figure out how this work) 
Note: if you want to anchor your version then use this commit instead of master https://github.com/luggit/react-native-config/commit/1eb6ac01991210ddad2989857359a0f6ee35d734
2. Follow exactly like the `README`, you don't need to add any code inside your `Podfile`
After `pod install` there will be some warning like this `[!] react-native-config has added 1 script phase.` (which mean you are doing this right)
2a. If your want to support `Info.plist`, replace `__RN_CONFIG_xxx` to `$(xxx)` inside your `Info.plist` file
3. Build and run your project like normal

On the side note, the `README` should be restructure for it is very confusing

**Comment by ninjz** [comment]
@s123121 I've done everything that you said. What does your `Pre-actions` script look like inside of schemes > Build > Pre-actions ? Mine looks like:

```
echo ".env.testing" > /tmp/envfile
${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
```

Not sure if i'm following the instruction correctly for when I want my configs in info.plist

**Comment by hkung77** [comment]
I'm also having some trouble with getting RN0.60.4 to work with this library. I get an error in the preprocessing Info.plist 
```
GeneratedInfoPlistDotEnv.h' file not found
```

It seems like there's so many different fixes each for different versions and if people have multiple envs.

Can we get some way of version controlling each solution and have an updated example. (it's currently at RN50). Perhaps just having a proper example for each version will alleviate all the issues popping up because this library doesn't work with this version.

**Comment by rexhuynh** [comment]
@s123121 thank you alot

**Comment by rexhuynh** [comment]
@ninjz you are correct remember that choose your target for Provide build settings form
<img width="1085" alt="Screen Shot 2019-07-30 at 1 41 46 PM" src="https://user-images.githubusercontent.com/13968562/62106803-5d505c00-b2d0-11e9-8ce5-c192c9c8a81e.png">

**Comment by ninjz** [comment]
@rexhuynh Thanks so much that seemed to solve my issue

**Comment by ZHIENDUS** [comment]
@rexhuynh you save my day

**Comment by wygkzqa** [comment]
> @Elvinra that worked for me!!
> 
> Another fix, if you install with npmjs, then
> ` yarn add react-native-config`
> Open podfile and add
> 
> ```ruby
> post_install do |installer|
>  installer.pods_project.targets.each do |target|
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>      phase.shell_script = "cd ../../"\
>      " && RNC_ROOT=./node_modules/react-native-config/"\
>      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
>      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
>      
>      target.build_phases << phase
>      target.build_phases.move(phase,0)
>    end
>  end
> end
> ```
> 
> `cd iOS && pod install`

Thanks. It works

**Comment by kdenz** [comment]
What I've done for RN 0.60.4 upgrade from 0.59.2 is basically 
1. Change `react-native-config` ver to master `"react-native-config": "github:luggit/react-native-config#master"` or lock commit to 1eb6ac0 as @s123121 said. Then `npm install` it
2. Remove `pod 'react-native-config', :path => '../node_modules/react-native-config'` in Podfile (if exists)
3. Remove the package link at `Link Binary with libraries` in your XCode Workspace
4. Add the following to Podfile, notice that it's `.rb` instead of `.ruby` for me (Thanks @mchudy)
```
post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'react-native-config'
     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
     phase.shell_script = "cd ../../"\
     " && RNC_ROOT=./node_modules/react-native-config/"\
     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
     
     target.build_phases << phase
     target.build_phases.move(phase,0)
   end
 end
end
```
5. run `pod install` at `ios` folder

**Comment by MPjsx** [comment]
@kdenz if remove script from **Podfile** it tun with `react-native run-ios`, but when try to archive - it fails with
`BuildProductsPath/GeneratedInfoPlistDotEnv.h' file not found`

**Comment by kdenz** [comment]
@Mlobaievskyi That's so wierd lol
I'm still trying to figure out this error 
```
/Users/kaiden-dragon/dev/dragon-frontend/react-native/node_modules/react-native-config/ios/ReactNativeConfig/ReadDotEnv.rb:27:in `join': no implicit conversion of nil into String (TypeError)
	from /Users/kaiden-dragon/dev/dragon-frontend/react-native/node_modules/react-native-config/ios/ReactNativeConfig/ReadDotEnv.rb:27:in `read_dot_env'
	from ./node_modules/react-native-config//ios/ReactNativeConfig/BuildDotenvConfig.rb:15:in `<main>'
reading env file from  and writing .m to 
going to read env file from root folder 
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by Mlobaievskyi** [comment]
Found solution


1) `yarn add react-native-config`
2) manually link  https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
3) add next to `react-native.config.js`
```
module.exports = {
  dependencies: {
    'react-native-config': {
      platforms: {
        ios: null
      }
    }
  }
}
```
4) `react-native run-ios` (archive also work)

**Comment by DVassilev** [comment]
Can't seem to get this running either. Followed various options from above and none have worked. Got the same error as @kdenz when I tried his one.

I'll see if I can get it going with a react-native init and see if I can figure out what's going on from there.

**Comment by kdenz** [comment]
@Mlobaievskyi @DVassilev good news here, @Mlobaievskyi 's solution worked for me, though I'm using the master branch version of react-native-config. (Not sure if 0.11.7 works as well) 
Basically follow the steps here to manually link the package https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
And then put this into `react-native.config.js` at root folder
```
module.exports = {
  dependencies: {
    'react-native-config': {
      platforms: {
        ios: null
      }
    }
  }
}
```
Remember to remove this snippet from `Podfile`
```
post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'react-native-config'
     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
     phase.shell_script = "cd ../../"\
     " && RNC_ROOT=./node_modules/react-native-config/"\
     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
     
     target.build_phases << phase
     target.build_phases.move(phase,0)
   end
 end
end
```
and the line `  pod 'react-native-config', :path => '../node_modules/react-native-config'`
then run `pod install` again

**Comment by aajkishore** [comment]
This behavior seems to be extremely inconsistent. Everything was working fine for me. Then I deleted the build folder, tried to build again, and this error came back. Then I unlinked the library
`react-native unlink react-native-config` which deleted this line
`pod 'react-native-config', :path => '../node_modules/react-native-config'` from Podfile.

And everything stated working again. Podfile does have the solution provided by @ravimaurya-nickelfox .

**Comment by kdenz** [comment]
What worked for me now on 0.60.4, inspired by @Mlobaievskyi  - 

1. Change `react-native-config` ver to master `"react-native-config": "github:luggit/react-native-config#master"` or lock commit to 1eb6ac0 as @s123121 said. Then `npm install` it
2. Basically follow the steps here to manually link the package https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking 
3. And then put the following into `react-native.config.js` at root folder (Not sure if necessary)
```
module.exports = {
  dependencies: {
    'react-native-config': {
      platforms: {
        ios: null
      }
    }
  }
}
```
4. Remember to remove this snippet from `Podfile`
```
post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'react-native-config'
     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
     phase.shell_script = "cd ../../"\
     " && RNC_ROOT=./node_modules/react-native-config/"\
     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
     
     target.build_phases << phase
     target.build_phases.move(phase,0)
   end
 end
end
```
and the line `pod 'react-native-config', :path => '../node_modules/react-native-config'` 
then run `pod install` again (To be safe you can delete `Podfile.lock` first)

Then I was getting `'GeneratedDotEnv.m' file not found.` error
After battling it a while I realized from this PR (https://github.com/luggit/react-native-config/commit/1eb6ac01991210ddad2989857359a0f6ee35d734) that I should remove all these preprocess settings. After that `'GeneratedDotEnv.m' file not found.` error is gone and it works for me.
![image](https://user-images.githubusercontent.com/12795428/62435361-6f1d7d80-b76e-11e9-84f7-f556000ae68d.png)

**Comment by ThomasLarge** [comment]
> ```ruby
> post_install do |installer|
>  installer.pods_project.targets.each do |target|
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>      phase.shell_script = "cd ../../"\
>      " && RNC_ROOT=./node_modules/react-native-config/"\
>      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
>      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
>      
>      target.build_phases << phase
>      target.build_phases.move(phase,0)
>    end
>  end
> end
> ```

THIS WORKS!!!!!!!!!!!!

**Comment by iba-ragi** [comment]
Do not trust the latest README.
If you want to use `info.plist` and `Js`,

1. Follow this [document](https://www.npmjs.com/package/react-native-config).
2. Put the following code in your podfile
3. Everything will work!!!!


> ```js
> post_install do |installer|
>  installer.pods_project.targets.each do |target|
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>       phase.shell_script = "cd ../../"\
>        " && RNC_ROOT=./node_modules/react-native-config/"\
>        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\> 
>       " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
> 
>       target.build_phases << phase
>       target.build_phases.move(phase,0)
>     end
>   end
>  end
> ```

**Comment by TakaKeiji** [comment]
> You are using react-native-config from npmjs, try to use this librairy directly from github
> yarn add https://github.com/luggit/react-native-config

This has worked for me correctly

**Comment by TrebuhD** [comment]
Can we have a new release from `master`? I don't feel comfortable hardcoding a repository link in my `package.json`.

**Comment by BrendanJMurray** [comment]
Chiming in here because this issue was invaluable in helping me to upgrade to `0.60.5` (and at this point I have this working in plist and in javascript):

If you remove preprocessor settings, don't expect any variables in your plist file to work. I did this because I simply needed my app to build so I could move onto other dependencies.

If you want to use variables in your plist and need to remove the preprocessor steps to get your app to run, make sure to follow @s123121's steps above.

**NOTE**: the readme is different from comments here that I've gotten to work, specifically the line: `${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"`

The README has the first operation in quotes which wasn't getting there for me, when I used the one posted by @ninjz this finally worked.

**Comment by wkoutre** [comment]
I second what @BrendanJMurray has offered.

**Comment by thepost** [comment]
> What worked for me now on 0.60.4, inspired by @Mlobaievskyi and @s123121 -
> 
> 1. Change `react-native-config` ver to master `"react-native-config": "github:luggit/react-native-config#master"` or lock commit to [1eb6ac0](https://github.com/luggit/react-native-config/commit/1eb6ac01991210ddad2989857359a0f6ee35d734) as @s123121 said. Then `npm install` it
> 2. Follow the steps here to manually link the package [https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking    ](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking%E2%80%A8)
> 3. And then put the following into `react-native.config.js` at root folder (Not sure if necessary)
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-config': {
>       platforms: {
>         ios: null
>       }
>     }
>   }
> }
> ```
> 
> 1. Remember to remove this snippet from `Podfile`
> 
> ```
> post_install do |installer|
>  installer.pods_project.targets.each do |target|
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>      phase.shell_script = "cd ../../"\
>      " && RNC_ROOT=./node_modules/react-native-config/"\
>      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
>      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
>      
>      target.build_phases << phase
>      target.build_phases.move(phase,0)
>    end
>  end
> end
> ```
> 
> and the line `pod 'react-native-config', :path => '../node_modules/react-native-config'`
> then run `pod install` again (To be safe you can delete `Podfile.lock` first)
> 
> Then I was getting `'GeneratedDotEnv.m' file not found.` error
> After battling it a while I realized from this PR ([1eb6ac0](https://github.com/luggit/react-native-config/commit/1eb6ac01991210ddad2989857359a0f6ee35d734)) that I should remove all these preprocess settings. After that `'GeneratedDotEnv.m' file not found.` error is gone and it works for me.
> ![image](https://user-images.githubusercontent.com/12795428/62435361-6f1d7d80-b76e-11e9-84f7-f556000ae68d.png)

There's got to be another solution that doesn't involve manual linking. It's a massive job when you have a lot of dependencies, and is more prone to human error.

**Comment by mehdihz** [comment]
I've changed the below configs in "Build Settings" of project

Info.plist Other Preprocessor Flags => -traditional
Info.plist Preprocessor Prefix File => ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h
Preprocess Info.plist File => Yes
and it worked

**Comment by felippepuhle** [comment]
@mehdihz npm version?

**Comment by MaximeConan** [comment]
> ```ruby
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>      phase.shell_script = "cd ../../"\
>      " && RNC_ROOT=./node_modules/react-native-config/"\
>      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
>      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
>      
>      target.build_phases << phase
>      target.build_phases.move(phase,0)
>    end
> ```

You're the best ! :D

**Comment by mehdihz** [comment]
> @mehdihz npm version?

Sorry for late answer. My npm version:  `6.9.0`

**Comment by bars0um** [comment]
I was beating my head at this for the better part of a day. Everything worked fine with little to no intervention on react 0.57 for me, moving to 0.60+ was a ball!

In any case what I needed was the following:

1- Store variables in the binary (e.g. URL and pinned public keys) and access them in JS (Config.X)
2- Pass variables to Info.plist (picked up by some sdks such as FB) $(MYVAR)
3- Pass variables through the bundler (bundle version info and other vars) ENVFILE=.env.x react-native run-ios

react-native-config did 1 and 2 for me, but for 3, I needed to use react-native-dotenv. 

Now my issue could be that these both read/write to /tmp/envfile but in essence this should not be an issue because you basically only want one .env.XYZ file to be consumed on any one build. 

For 1, I needed only to import the Config variable and use as needed. Between builds I need to rebuild since this is passed through the binary.

For 2, I needed to do some acrobatics and to stand on my head a bit. Basically the documentation seems to have changed and you no longer should be using the prefix __RN_CONFIG_VARNAME but instead $(VARNAME) only. 

Here also you need to make sure that your xcconfig file references the tmp.xcconfig file which should be generated by an early build phase step that you have to create 

```
${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig
```

When I ran this command in terminal alone I noticed that it generated an empty tmp.xcconfig which was simply because I had not created a /tmp/envfile. Now my scheme build pre-action does this:
```
export ENVFILE=.env.test
echo $ENVFILE > /tmp/envfile   
echo $ENVFILE > /tmp/dotenv
```

So it's not that the build doesn't have a /tmp/envfile to work with...at this point I figured it must have been deleted somewhere in the series of scripts running. 

Reviewing the build logs when I had issues with vars not making it into the package, I noticed a subtle message: 

**************************
*** Missing .env file ****
**************************

In the same log I noted that a previous run of BuildXCConfig.rb had no issues. Reviewing BuildXCConfig I realized that the last step deletes the /tmp/envfile...which of course was the crux of the problem, at least for my specific issue, I've create a pull request here for this: https://github.com/luggit/react-native-config/pull/404

The additional step needed for 2 to work properly is to make sure that your Project->Info->Configurations configured file (for me Pods-Project-Prod.xcconfig) calls 
```
#include? "tmp.xcconfig"
```
at the top. 

**Note** this gets stamped any time you do a _pod install_ so we'd need a post_install step to put it back in.

For 3 I still can't find a very clean way of doing this for xcode. At present you need the scheme build pre-action to create the /tmp/dotenv file, but to pass ENVFILE to the bundler, I basically had to modify the node_modules/react-native/scripts/node-binary.sh and add the export there:

```
export ENVFILE=$(cat /tmp/dotenv)
```

In React < 0.60 I could add this bit to the React.xproj packager build phase, however with React > 0.60 the logic of the scripts have changed.

**Comment by EliYenn** [comment]
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if(target.name=='Pods-YOURPROJECTTARGET')
          puts "Updating #{target.name} for react-native-config configs to be included"
          target.build_configurations.each do |config|
              xcconfig_path = config.base_configuration_reference.real_path
              xcconfig = File.read(xcconfig_path)
              nativeconfig = '#include? "tmp.xcconfig"' + "\r\n" + xcconfig
              File.open(xcconfig_path, "w") { |file|  file << nativeconfig }
          end      
        end
  end
end

After running, it can be used by using acts-native run-ios, but after deleting ipa, the edit config is empty

**Comment by selcukitmis** [comment]
> Clear xcode cache with

**enter** shift + option + cmd + k and **clean**

**Comment by jayzyaj** [comment]
I just upgraded my React Native version to **0.61.4** and react-native-config **^0.12.0**. @kdenz solution worked for me.

**Comment by tmaly1980** [comment]
> @Elvinra that worked for me!!
> 
> Another fix, if you install with npmjs, then
> ` yarn add react-native-config`
> Open podfile and add
> 
> ```ruby
> post_install do |installer|
>  installer.pods_project.targets.each do |target|
>    if target.name == 'react-native-config'
>      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
>      phase.shell_script = "cd ../../"\
>      " && RNC_ROOT=./node_modules/react-native-config/"\
>      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
>      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
>      
>      target.build_phases << phase
>      target.build_phases.move(phase,0)
>    end
>  end
> end
> ```
> 
> `cd iOS && pod install`

I had to rename BuildDotenvConfig.ruby to BuildDotenvConfig.rb

**Comment by mguay22** [comment]
Thank you! @tmaly1980

**Comment by alexpyoung** [comment]
FYI on RN 0.61.2:

In addition to https://github.com/luggit/react-native-config/issues/365#issuecomment-514487016 when using `v0.11.7`, `v0.12.0` alleviates the need for this patch, after some additional [small changes to your project](https://github.com/luggit/react-native-config/issues/414#issuecomment-563958339)

**Comment by AdrianBordeianu** [comment]
> The library is not working with `RN 0.60.4`, automatic linking is not working. If I try to link manually, it throws errors. On `pod install` it produces error `'GeneratedDotEnv.m' file not found`.
> 
> Any help? 🆘

For me, the problem was that ProjectTests target had the Preprocessor Prefix File set the same as the project, and it should be empty.

**Comment by khalilTN** [comment]
Is there a solution without having to add code to Podfile ?

**Comment by gevgasparyan** [comment]
If you are using Pods just add (without `react-native link react-native-config`)

`pod 'react-native-config', :path => '../node_modules/react-native-config/react-native-config.podspec'`
in your Podfile

**Comment by pragneshpj** [comment]
I got .env value in AppDelegate.m
but didn't get in info.plist.
NSDictionary *config = [ReactNativeConfig env];
NSLog(@"Configure: %@", config);

"react-native": "0.61.5"
"react-native-config": "luggit/react-native-config#master",

can anyone help me. (Please share steps)

Thanks

**Comment by tmaly1980** [comment]
I was getting the "ld: library not found for -lReactNativeConfig" error after switching over to CocoaPods. I removed ReactNativeConfig from the Libraries folder, but forgot to clean up "Link Binary with Libraries" under Build Phases.

**Comment by gilador** [comment]
> ```ruby
> RNC_ROOT=./node_modules/react-native-config/
> ```

I had to edit `" && RNC_ROOT=./node_modules/react-native-config/"\` to without '/' at the end =>

**Comment by okcoker** [comment]
I'm using react-native-config 1.4.1 and was running into the empty object problem on ios so I added a new run script and got the config correctly populated as expected:

```sh
if [ "${CONFIGURATION}" = "Release" ]; then
    export ENVFILE="$SRCROOT/../.env.production"
else
    export ENVFILE="$SRCROOT/../.env.development"
fi
```

<img width="605" alt="Screen Shot 2020-12-07 at 7 06 25 AM" src="https://user-images.githubusercontent.com/1030830/101349216-0743df00-385b-11eb-8bc8-22a90c5a5465.png">

**Comment by 0011001011** [comment]
this should be /open

**Comment by timorss** [comment]
> @ninjz you are correct remember that choose your target for Provide build settings form <img alt="Screen Shot 2019-07-30 at 1 41 46 PM" width="1085" src="https://user-images.githubusercontent.com/13968562/62106803-5d505c00-b2d0-11e9-8ce5-c192c9c8a81e.png">

Thanks!!
