### ISSUE TITLE
[RN 62] Variables are undefined

### ISSUE THREAD

**Issue by daviddelusenet** [luggit/react-native-config#460]
I installed `react-native-config` version `1.2.0` and added a `.env` file to the root of my project. This `.env` file contains the following:

```bash
REACT_APP_LAST_FM_API_KEY=some_key_here
REACT_APP_LAST_FM_SHARED_KEY=some_shared_key_here
```

In my `App.tsx` I've the following:

```tsx
import Config from 'react-native-config';

console.log(Config.REACT_APP_LAST_FM_API_KEY) // undefined;
```

When I do `console.log(Config)` I get the following:

```tsx
{"APPLICATION_ID": "com.mobile", "BUILD_TYPE": "debug", "DEBUG": true, "FLAVOR": "", "VERSION_CODE": 1, "VERSION_NAME": "1.0", "getConstants": [Function anonymous]}
```

Am I missing something?

Please let me know if you need any more information and thanks in advance!

**Comment by daviddelusenet** [comment]
I tried hardcoding the `.env` file in my script I use to start RN:

```bash
ENVFILE=.env react-native run-android
```

Still missing the contents of my `.env` file when I do `console.log(Config)`.

**Comment by tomdmason** [comment]
Did you add this to your build.gradle?
`apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`

Otherwise your setup looks basically identical to mine

**Comment by daviddelusenet** [comment]
We did and that fixed it, thanks!

This package works great but the documentation is a little bit unclear in my opinion.

**Comment by BIRahul** [comment]
@tomdmason yes I did that but still same issue

**Comment by akiladevinda** [comment]
Still the same issue. Any fixes ?

**Comment by BIRahul** [comment]
@akiladevinda can you show me your .env file?

**Comment by akiladevinda** [comment]
CHANNEL: APP
  CLIENT_ID: client
  CLIENT_SECRET: secretSample
  POST_CODE_ANYWHERE_KEY: swe3-ds34-ssfd

**Comment by BIRahul** [comment]
@akiladevinda  If you changed-
 
CHANNEL: APP
CLIENT_ID: client
CLIENT_SECRET: secretSample
POST_CODE_ANYWHERE_KEY: swe3-ds34-ssfd

to 

API_URL=https://myapi.com
GOOGLE_MAPS_API_KEY=abcdefgh

It will start working.

**Comment by akiladevinda** [comment]
Thanks it works now

**Comment by anhdo9797** [comment]
I same issue

This is my `app/build.gradle`
```
project.ext.defaultEnvFile="env/.env"
project.ext.envConfigFiles = [
    SADevDebug: "env/SA/.env.dev",
    SADevRelease: "env/SA/.env.dev",
    SAStDebug: "env/SA/.env.staging",
    SAStRelease: "env/SA/.env.staging",
]
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```
This is my env folder
<img width="455" alt="Screen Shot 2023-07-04 at 11 31 47" src="https://github.com/luggit/react-native-config/assets/60549336/b401ef35-c782-4857-a976-cead3c6b81ed">

**Comment by juned-miah** [comment]
I have followed the guide but my `Config` object is always empty. I also notice that `NativeModules.RNCConfigModule` is `undefined`. I can see that the module has been loaded as the package appears in the generated `PackageList` for the android build, yet it doesn't appear in the `NativeModules` object in JS.

I am using React native 0.72.3 and react-native-config 1.5.1 so auto-linking should work.

I have set up the environment files and set them in the `android/app/build.gradle` under `project.ext.envConfigFiles`. The library is able to find the correct environment file and load it inside `node_modules/react-native-config/android/dotenv.gradle` but then `Config` is not set for some reason.

Any help with this?

**Comment by amerllica** [comment]
Dear @juned-miah, I got this issue now, your problem was exactly one year ago and I can't find any update or fix.

**Comment by saeid-elio** [comment]
> Did you add this to your build.gradle? `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`
> 
> Otherwise your setup looks basically identical to mine

This solved my problem! How come this is not mentioned in readme.md?!

**Comment by mlazari** [comment]
@amerllica In my case it was caused by me missing the "Advanced Android Setup" step about adding this to `android/app/build.gradle`:
```
defaultConfig {
    ...
    resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST_XML"
}
````
Without it, the class name at https://github.com/lugg/react-native-config/blob/v1.5.3/android/src/main/java/com/lugg/RNCConfig/RNCConfigModule.java#L35 was wrong causing it to end up in the catch clause at https://github.com/lugg/react-native-config/blob/v1.5.3/android/src/main/java/com/lugg/RNCConfig/RNCConfigModule.java#L47.

**Comment by amerllica** [comment]
Dear @mlazari, Can you send a PR to fix it?

**Comment by amerllica** [comment]
Dear @mlazari, Can you send a PR? I promise to review it as soon as possible. 🚀

**Comment by mlazari** [comment]
@amerllica It was something I missed in my project, not in the library. It was a new project with 2 flavors - staging and production. In the staging flavor the application id (`com.example.myapp.stage`) was different from package name (`com.example.myapp`), that's why it was not finding the `BuildConfig` class in the library and that was causing `NativeModules.RNCConfigModule` to be null at https://github.com/lugg/react-native-config/blob/v1.5.3/index.js#L8 thus the exported Config was an empty object.
This is already documented in README in the "Advanced Android Setup" so not sure what I could add. I just thought my comment could help someone since it took me a while to understand why the variables in config are undefined.

**Comment by genesisbell** [comment]
> Did you add this to your build.gradle? `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`
> 
> Otherwise your setup looks basically identical to mine

This has to be in your android/app/build.gradle

**Comment by amerllica** [comment]
Dear @genesisbell, please mention who you want to talk to, otherwise that user cannot get a notification.

Anyway, the line `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"` must be inside `build.gradle` so he definitely meant `app/build.gradle` not the project level. That's an obvious thing.

**Comment by geek-ibrar** [comment]
> @amerllica It was something I missed in my project, not in the library. It was a new project with 2 flavors - staging and production. In the staging flavor the application id (`com.example.myapp.stage`) was different from package name (`com.example.myapp`), that's why it was not finding the `BuildConfig` class (it was looking for `com.example.app.stage.BuildConfig` instead of `com.example.app.BuildConfig`) in the library and that was causing `NativeModules.RNCConfigModule` to be null at https://github.com/lugg/react-native-config/blob/v1.5.3/index.js#L8 thus the exported Config was an empty object. Once I added `resValue "string", "build_config_package", "com.example.app"` in `android/app/build.gradle` as per documentation it fixed my issue. This is already documented in README in the "Advanced Android Setup" so not sure what I could add. I just thought my comment could help someone since it took me a while to understand why the variables in config are undefined.

Thank you so much, after spending a complete day on this issue. Your comment finally helped.
