### ISSUE TITLE
Stale data from different app 😲

### ISSUE THREAD

**Issue by dani-z** [luggit/react-native-config#509]
Hello everyone. 

I encounter an extremely weird problem with one of my apps I'm working on now: I am getting data that I have in a different app! This is so strange and haven't seen nothing like it.

So if I console log Config, I can see env entries I have in a different app that's using react-native-config package

Is there a solution for this?

Many thanks.

**Comment by rares-lupascu** [comment]
make sure u do not use the code to copy the .env from the docs ... use this one:

```
if [ "${ENVFILE}" ]; then echo "${ENVFILE}" > /tmp/envfile ; else echo ".env.development" > /tmp/envfile; fi
```

**Comment by jlandrum** [comment]
I suddenly started having this problem. I've erased every copy of the env file it's loading, cleared the Metro cache, reinstalled all pods and node_modules, deleted /tmp/envfile and it's still loading the .env file that doesn't even exist. Since there is no logical reason it should even know about this file, there's no obvious steps for debugging.

Xcode is generating a new .plist with the correct file, the /tmp/envfile is correct after rebuilding, so I'm at a complete loss.

**Comment by dani-z** [comment]
@rares-lupascu Yeah it seems some other (older) app was creating the /tmp and the new app was using that. After a `rm -rf /tmp/envfile` and rebuild I get the right env vars. 🙌 
I think can be closed now.
