### ISSUE TITLE
XCode support for plist files

### ISSUE THREAD

**Issue by danielweinmann** [luggit/react-native-config#6]
@pedro, is it possible to accomplish that? I believe this is the only missing part for us to really enjoy the 12 factor love in React Native :D

Again, if you instruct me I can try to send PRs.

**Comment by pedro** [comment]
Hey!

My initial hope was to generate a `.xcconfig` file from the build script, but that doesn't seem possible :{ these files are fairly static.

@kipricker suggested using scheme environment vars, which is interesting because this would play well with the way [we're suggesting developers to pick different .env files](https://github.com/luggg/react-native-config/issues/5). I gave this a try and didn't get anywhere so far though, so will need some exploration/advice.

Another path I want to explore is to dynamically generate a `plist` with the env contents, and see if we can import/merge that into `Info.plist` somehow.

As you might be able to tell I'm not skilled in Xcode at all, so still figuring these out as we go :} Needless to say any input/suggestion/help here is very welcome!

**Comment by danielweinmann** [comment]
Yeah, in my project I ended up generating an Info.plist from a template inside an automated build script. It works for me, but it's not very elegant :P

**Comment by migueloller** [comment]
Hey @pedro, have you thought of using [plist](https://github.com/TooTallNate/plist.js) and having a build pre-action to replace environment variables in Info.plist and then place them back in a post-action?

**Comment by pedro** [comment]
Plist support documented in the readme, closing!

Thanks folks,
