### ISSUE TITLE
.env should be a .properties file

### ISSUE THREAD

**Issue by adambene** [luggit/react-native-config#85]
The .env file should be a .properties file or some other standard.

Or if you don't want to follow any standards then it would be really helpful to define the grammar in the readme.

It would clarify for example the followings:

- how to escape
- how to add comments
etc.

**Comment by j2kun** [comment]
This project should be using the js `dotenv` module to load the config. Otherwise subtle things break like:

```
# in .env
ENABLE_ANALYTICS=false
```

This is currently loaded into the Config object as a string, not a truthy argument as is standard for `.env` files.

```
# in js
if (Config.ENABLE_ANALYTICS) {
   // ... evaluated
}
```

**Comment by adambene** [comment]
@j2kun dotenv does not support smart type casting if I am right: https://github.com/motdotla/dotenv/pull/96

**Comment by j2kun** [comment]
@adambene right you are. I guess I'll have to do my own parsing :(

**Comment by adambene** [comment]
Anyway it would be essential to support any of the standards.

**Comment by ohlsont** [comment]
A big problem for me is that .env files does not support any ascii signs outside US-ASCII :(. Any swedish åäö letters etc are saved as questionmarks.

**Comment by ohlsont** [comment]
This fixes my problems anyway: https://github.com/luggit/react-native-config/pull/113

**Comment by pedro** [comment]
+1, UTF should be supported now!

Otherwise yes, all env vars are strings.

`.properties` sounds interesting, but I don't like that it's so tied to Java and Android.

Seeing that `.env` made into [React itself (for non-native apps)](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env) I think we should stick to it.

Casting the config or comparing to strings only seems pretty straight forward, or at least easier than introducing a diff format for defining the environment that works in all platforms.

Thanks folks!
