### ISSUE TITLE
Cannot build in xcode

### ISSUE THREAD

**Issue by iamakimmer** [luggit/react-native-config#92]
I'm getting this error while buliding

```
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/mattkim/.rvm/gems/ruby-2.2.3/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/mattkim/.rvm/gems/ruby-2.2.3/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

/Users/mattkim/Library/Developer/Xcode/DerivedData/BroadwayBuddy-dkymcolbmsxjcoehdcymruxggajw/Build/Intermediates/ReactNativeConfig.build/Debug-iphoneos/ReactNativeConfig.build/Script-EBE4E8281C7BF689000F8875.sh: line 2: 32806 Abort trap: 6           ./ReactNativeConfig/BuildDotenvConfig.ruby
Command /bin/sh failed with exit code 134

```
Any suggestions?  I'm able to build successfully via react-native run-ios/android, but not within xcode due to this error

**Comment by iamakimmer** [comment]
The suggestion in https://github.com/luggit/react-native-config/issues/84 also resolves this issue

**Comment by InteractiveLogic** [comment]
On my machine, I didn't have any problems building and archiving, but a teammate did. When he attempted to do an archive in Xcode, it would crash with the following error message:

```
dyld: lazy symbol binding failed: Symbol not found: _ruby_run
  Referenced from: /usr/local/bin/ruby
  Expected in: /usr/lib/libruby.dylib

dyld: Symbol not found: _ruby_run
  Referenced from: /usr/local/bin/ruby
  Expected in: /usr/lib/libruby.dylib

/Users/USER_NAME_HERE/Library/Developer/Xcode/DerivedData/Technician-dqmaqllguuiqfvhguxgdvwnhqnwf/Build/Intermediates/ArchiveIntermediates/Technician-STAGING/IntermediateBuildFilesPath/ReactNativeConfig.build/Release-iphoneos/ReactNativeConfig.build/Script-EBE4E8281C7BF689000F8875.sh: line 2: 11682 Trace/BPT trap: 5       ./ReactNativeConfig/BuildDotenvConfig.ruby
Command /bin/sh failed with exit code 133
```

We took a few stabs at trying to resolve it with no success, such as trying the solution suggested in #84, which didn't help in his case --  it still crashed on build/archive.

I pulled down a totally clean set of code just to make sure it was building properly and wasn't working because of cruft in my other directory, and it still built and archived just fine on my system.

So the last thing he did was to _update his system ruby using brew_. After updating his system ruby (not rvm), the archive completed successfully!

So I thought I'd pass this on, just in case the suggestion in the other issue didn't work for other developers. Worth a try to update your system ruby

Hope this helps!

**Comment by jacklam718** [comment]
@InteractiveLogic Works for me. Thanks.

**Comment by pedro** [comment]
:+1:! Should be working normally on the latest version.

Thanks,
